service.key=1234
gateway=false
service.web.gateway.url=http://localhost:8080
service.web.user.url=http://localhost:8300
service.web.model.url=http://localhost:8301
service.web.file.url=http://localhost:8302
service.web.machine.url=http://localhost:8303

