/*
 * Copyright 2019 osvaldo.rodriguez.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.retina.view.frame;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.retina.model.Model;

/**
 *
 * @author osvaldo.rodriguez
 */
public final class Main extends JFrame {
    
    static Logger logger = LogManager.getLogger(Main.class.getName());
    private Model model = new Model();
    public org.retina.view.dialog.Image imageDialog = new org.retina.view.dialog.Image(this,false);
    public org.retina.view.dialog.Rectangle rectangleDialog = new org.retina.view.dialog.Rectangle(this,false);
    public org.retina.view.dialog.Page pageDialog = new org.retina.view.dialog.Page(this,false);
    public org.retina.view.dialog.New newDialog = new org.retina.view.dialog.New(this,false);
    public org.retina.view.dialog.Open openDialog = new org.retina.view.dialog.Open(this,false);
    public org.retina.view.dialog.Save saveDialog = new org.retina.view.dialog.Save(this,false);
    public org.retina.view.dialog.output.Zooniverse exportZooniverseDialog = new org.retina.view.dialog.output.Zooniverse(this,false);
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        URL url = getClass().getResource("/icon.gif");
        logger.debug(url);
        Image image = Toolkit.getDefaultToolkit().getImage(url);
        logger.debug(image);
        this.setIconImage(image);
        this.setModel();
        this.init();
    }
    
    public Model getModel() {
        return this.model;
    }
    
    public void setModel(Model model) {
        this.model = model;
    }
    
    public void setModel() {
        logger.debug("setModel()");
        this.imagePanel.setModel(this.model);
        this.pagePanel.setModel(this.model);
        this.imageDialog.setModel(this.model);
        this.rectangleDialog.setModel(this.model);
        this.openDialog.setModel(this.model);
        this.saveDialog.setModel(this.model);
        this.pageDialog.setModel(this.model);
        this.exportZooniverseDialog.setModel(this.model);
    }
    
    public void init(){
        logger.debug("init()");
        this.setTitle("Retina");
        this.imagePanel.setMain(this);
        this.imagePanel.setFocusable(true);
        this.imagePanel.requestFocusInWindow();
        this.imageDialog.setVisible(true);
        this.rectangleDialog.setVisible(true);

    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePageTabbedPane = new javax.swing.JTabbedPane();
        imagePanel = new org.retina.view.panel.Image();
        pagePanel = new org.retina.view.panel.Page();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        imageMenu = new javax.swing.JMenu();
        sizeMenuItem = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        dialogMenu = new javax.swing.JMenu();
        pageMenuItem = new javax.swing.JMenuItem();
        imageMenuItem = new javax.swing.JMenuItem();
        rectangleMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        imagePageTabbedPane.addTab("Image", imagePanel);

        javax.swing.GroupLayout pagePanelLayout = new javax.swing.GroupLayout(pagePanel);
        pagePanel.setLayout(pagePanelLayout);
        pagePanelLayout.setHorizontalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pagePanelLayout.setVerticalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        imagePageTabbedPane.addTab("Page", pagePanel);

        fileMenu.setText("File");

        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As");
        fileMenu.add(saveAsMenuItem);

        jMenu1.setText("Import");

        jMenuItem1.setText("Image");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Zooniverse");
        jMenu1.add(jMenuItem2);

        fileMenu.add(jMenu1);

        jMenu2.setText("Export");

        jMenuItem3.setText("Zooniverse");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Excel");
        jMenu2.add(jMenuItem4);

        fileMenu.add(jMenu2);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");
        jMenuBar1.add(editMenu);

        imageMenu.setText("Image");

        sizeMenuItem.setText("Size");
        imageMenu.add(sizeMenuItem);

        jMenuBar1.add(imageMenu);

        windowMenu.setText("Window");

        dialogMenu.setText("Dialog");

        pageMenuItem.setText("Page");
        pageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageMenuItemActionPerformed(evt);
            }
        });
        dialogMenu.add(pageMenuItem);

        imageMenuItem.setText("Image");
        imageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageMenuItemActionPerformed(evt);
            }
        });
        dialogMenu.add(imageMenuItem);

        rectangleMenuItem.setText("Rectangle");
        rectangleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleMenuItemActionPerformed(evt);
            }
        });
        dialogMenu.add(rectangleMenuItem);

        windowMenu.add(dialogMenu);

        jMenuBar1.add(windowMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePageTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePageTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        this.newDialog.setVisible(true);
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        this.saveDialog.setVisible(true); 
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        this.openDialog.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void imageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageMenuItemActionPerformed
        this.imageDialog.setVisible(true);
    }//GEN-LAST:event_imageMenuItemActionPerformed

    private void rectangleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleMenuItemActionPerformed
        this.rectangleDialog.setVisible(true);
    }//GEN-LAST:event_rectangleMenuItemActionPerformed

    private void pageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageMenuItemActionPerformed
        this.pageDialog.setVisible(true);
    }//GEN-LAST:event_pageMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.exportZooniverseDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        logger.info("Retina starting...");
//        final Main main = new Main();
//        Splash splash = new Splash("/splash.png", main, 4000);
//        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            logger.error(ex);
//        } catch (InstantiationException ex) {
//            logger.error(ex);
//        } catch (IllegalAccessException ex) {
//            logger.error(ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.error(ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                main.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dialogMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu imageMenu;
    private javax.swing.JMenuItem imageMenuItem;
    private javax.swing.JTabbedPane imagePageTabbedPane;
    private org.retina.view.panel.Image imagePanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pageMenuItem;
    private org.retina.view.panel.Page pagePanel;
    private javax.swing.JMenuItem rectangleMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem sizeMenuItem;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables
}
