/*
 * Copyright 2019 osvaldo.rodriguez.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.meritoki.retina.application.desktop.view.frame;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import com.meritoki.retina.application.desktop.model.Model;
import com.meritoki.retina.application.desktop.model.document.Document;
import com.meritoki.retina.application.desktop.view.dialog.user.Login;
import com.meritoki.retina.application.desktop.view.dialog.user.Register;

/**
 *
 * @author osvaldo.rodriguez
 */
public final class Main extends JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 4699683145704846741L;
    private static Logger logger = LogManager.getLogger(Main.class.getName());
    public Model model = null;
    public Login loginDialog = new Login(this,false);
    public Register registerDialog = new Register(this,false);
    public com.meritoki.retina.application.desktop.view.dialog.Open openDialog = null;
    public com.meritoki.retina.application.desktop.view.dialog.SaveAs saveAsDialog = null; 
    public com.meritoki.retina.application.desktop.view.dialog.image.Import imageImportDialog = null;
    public com.meritoki.retina.application.desktop.view.dialog.Image imageDialog = new com.meritoki.retina.application.desktop.view.dialog.Image(this, false);
    public com.meritoki.retina.application.desktop.view.dialog.Selection selectionDialog = new com.meritoki.retina.application.desktop.view.dialog.Selection(this, false);
    public com.meritoki.retina.application.desktop.view.dialog.Matrix matrixDialog = new com.meritoki.retina.application.desktop.view.dialog.Matrix(this, false);
    public com.meritoki.retina.application.desktop.view.dialog.zooniverse.Export exportZooniverseDialog = new com.meritoki.retina.application.desktop.view.dialog.zooniverse.Export(this, false);
    public com.meritoki.retina.application.desktop.view.dialog.zooniverse.Import importZooniverseDialog = new com.meritoki.retina.application.desktop.view.dialog.zooniverse.Import(this, false);
    
    public Main() {
        initComponents();
        URL url = getClass().getResource("/icon.gif");
        logger.debug(url);
        Image image = Toolkit.getDefaultToolkit().getImage(url);
        logger.debug(image);
        this.setIconImage(image);
        this.setModel(new Model());
        this.init();
        
    }

    public void setModel(Model model) {
        logger.debug("setModel(" + model + ")");
        this.model = model;
        this.imagePanel.setModel(this.model);
        this.matrixPanel.setModel(this.model);
        this.imageDialog.setModel(this.model);
        this.selectionDialog.setModel(this.model);
        this.matrixDialog.setModel(this.model);
        this.exportZooniverseDialog.setModel(this.model);
        this.importZooniverseDialog.setModel(this.model);
        this.registerDialog.setModel(this.model);
        this.registerDialog.setLoginDialog(this.loginDialog);
        this.loginDialog.setModel(this.model);
        this.loginDialog.setRegisterDialog(this.registerDialog);
        if(this.model.variable.newUser) {
        	this.registerDialog.setVisible(true);
        } else {
//        	this.loginDialog.setVisible(true);
        }
    }

    public void init() {
        logger.debug("init()");
        this.setTitle("Retina Desktop Application");
        this.imagePanel.setMain(this);
        this.imagePanel.setFocusable(true);
        this.imagePanel.requestFocusInWindow();
        this.imageDialog.init();
        this.selectionDialog.init();
//        this.imageDialog.setVisible(true);
//        this.shapeDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePageTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagePanel = new com.meritoki.retina.application.desktop.view.panel.Image();
        jScrollPane2 = new javax.swing.JScrollPane();
        matrixPanel = new com.meritoki.retina.application.desktop.view.panel.Matrix();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        importMenu = new javax.swing.JMenu();
        importImageMenuItem = new javax.swing.JMenuItem();
        importZooniverseMenuItem = new javax.swing.JMenuItem();
        exportMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        dialogMenu = new javax.swing.JMenu();
        pageMenuItem = new javax.swing.JMenuItem();
        imageMenuItem = new javax.swing.JMenuItem();
        rectangleMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1028, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imagePanel);

        imagePageTabbedPane.addTab("Image", jScrollPane1);

        javax.swing.GroupLayout matrixPanelLayout = new javax.swing.GroupLayout(matrixPanel);
        matrixPanel.setLayout(matrixPanelLayout);
        matrixPanelLayout.setHorizontalGroup(
            matrixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1028, Short.MAX_VALUE)
        );
        matrixPanelLayout.setVerticalGroup(
            matrixPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(matrixPanel);

        imagePageTabbedPane.addTab("Matrix", jScrollPane2);

        fileMenu.setText("File");

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loginMenuItem);

        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        importMenu.setText("Import");

        importImageMenuItem.setText("Image");
        importImageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importImageMenuItemActionPerformed(evt);
            }
        });
        importMenu.add(importImageMenuItem);

        importZooniverseMenuItem.setText("Zooniverse");
        importZooniverseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importZooniverseMenuItemActionPerformed(evt);
            }
        });
        importMenu.add(importZooniverseMenuItem);

        fileMenu.add(importMenu);

        exportMenu.setText("Export");

        jMenuItem3.setText("Zooniverse");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        exportMenu.add(jMenuItem3);

        jMenuItem4.setText("Excel");
        exportMenu.add(jMenuItem4);

        fileMenu.add(exportMenu);

        mainMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        undoMenuItem.setText("Undo");
        undoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoMenuItem);

        redoMenuItem.setText("Redo");
        redoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(redoMenuItem);

        mainMenuBar.add(editMenu);

        windowMenu.setText("Window");

        dialogMenu.setText("Dialog");

        pageMenuItem.setText("Page");
        pageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageMenuItemActionPerformed(evt);
            }
        });
        dialogMenu.add(pageMenuItem);

        imageMenuItem.setText("Image");
        imageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageMenuItemActionPerformed(evt);
            }
        });
        dialogMenu.add(imageMenuItem);

        rectangleMenuItem.setText("Rectangle");
        rectangleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleMenuItemActionPerformed(evt);
            }
        });
        dialogMenu.add(rectangleMenuItem);

        windowMenu.add(dialogMenu);

        mainMenuBar.add(windowMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePageTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePageTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        this.model.setDocument(new Document());
//        this.imageImportDialog.setVisible(true);
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
    	
//    	DocumentController.save(file, this.model.getDocument());    
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
    	this.openDialog = new com.meritoki.retina.application.desktop.view.dialog.Open(this, false);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void imageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageMenuItemActionPerformed
        this.imageDialog.setVisible(true);
    }//GEN-LAST:event_imageMenuItemActionPerformed

    private void rectangleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleMenuItemActionPerformed
        this.selectionDialog.setVisible(true);
    }//GEN-LAST:event_rectangleMenuItemActionPerformed

    private void pageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageMenuItemActionPerformed
        this.matrixDialog.setVisible(true);
    }//GEN-LAST:event_pageMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.exportZooniverseDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
    	this.saveAsDialog = new com.meritoki.retina.application.desktop.view.dialog.SaveAs(this, false);
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void importImageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importImageMenuItemActionPerformed
        this.imageImportDialog = new com.meritoki.retina.application.desktop.view.dialog.image.Import(this, false);
    }//GEN-LAST:event_importImageMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        this.loginDialog.setVisible(true);
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuItemActionPerformed
        // TODO add your handling code here:
    	
    }//GEN-LAST:event_undoMenuItemActionPerformed

    private void redoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redoMenuItemActionPerformed

    private void importZooniverseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importZooniverseMenuItemActionPerformed
        this.importZooniverseDialog.setVisible(true);
    }//GEN-LAST:event_importZooniverseMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        logger.info("Retina starting...");
//        final Main main = new Main();
//        Splash splash = new Splash("/splash.png", main, 4000);
//        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            logger.error(ex);
//        } catch (InstantiationException ex) {
//            logger.error(ex);
//        } catch (IllegalAccessException ex) {
//            logger.error(ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.error(ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                main.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dialogMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu exportMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem imageMenuItem;
    private javax.swing.JTabbedPane imagePageTabbedPane;
    private com.meritoki.retina.application.desktop.view.panel.Image imagePanel;
    private javax.swing.JMenuItem importImageMenuItem;
    private javax.swing.JMenu importMenu;
    private javax.swing.JMenuItem importZooniverseMenuItem;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private com.meritoki.retina.application.desktop.view.panel.Matrix matrixPanel;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pageMenuItem;
    private javax.swing.JMenuItem rectangleMenuItem;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem undoMenuItem;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables
}
