/*
 * Copyright 2019 osvaldo.rodriguez.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.meritoki.app.desktop.retina.view.panel;

import java.awt.Graphics;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.meritoki.app.desktop.retina.controller.parser.Parser;
import com.meritoki.app.desktop.retina.model.Model;
import com.meritoki.app.desktop.retina.model.document.Document;
import com.meritoki.app.desktop.retina.model.document.Page;
import com.meritoki.app.desktop.retina.model.document.Project;
import com.meritoki.app.desktop.retina.view.frame.MainFrame;

/**
 *
 * @author osvaldo.rodriguez
 */
public class TablePanel extends javax.swing.JPanel {

	private static Logger logger = LogManager.getLogger(TablePanel.class.getName());
	private Model model = null;
	private MainFrame main = null;

	/**
	 * Creates new form Table
	 */
	public TablePanel() {
		initComponents();
	}
	
	public void setMain(MainFrame main) {
		this.main = main;
	}

	public void setModel(Model model) {
		logger.debug("setModel(" + model + ")");
		this.model = model;
		this.init();
	}

	public void init() {
		this.initDataTable();
	}

	public void initDataTable() {
		logger.info("initDataTable()");
		Parser parser = new Parser();
		Document document = (this.model != null) ? this.model.getDocument() : null;
		Project project = (document != null) ? document.getProject() : null;
		Page page = (project != null) ? project.getPage() : null;
		if (page != null) {
			logger.info("initDataTable() page");
//			Object[][] objectMatrix = parser.parseData(page.getShapeMatrixShapeList());
//			Object[] stringArray = parser.parseColumn(page.getShapeMatrixShapeList());
			Object[] modelArray = parser.getModel(page.getShapeMatrixShapeList());
			DefaultTableModel model = new javax.swing.table.DefaultTableModel((Object[][])modelArray[1], (Object[])modelArray[0]);
			this.dataTable.setModel(model);
//                        this.dataTable.getColumnModel().getColumn(4).setPreferredWidth(30);
//                        this.dataTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
//                        this.dataTable = new JTable(objectMatrix,stringArray);
//			this.repaint();
		}
	}
	

	@Override
	public void paintComponent(Graphics g) {
		this.initDataTable();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
