/*
 * Copyright 2019 osvaldo.rodriguez.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.meritoki.retina.application.desktop.view.dialog;

import java.util.List;
import javax.swing.DefaultListModel;
import org.apache.logging.log4j.LogManager;

import com.meritoki.retina.application.desktop.model.Model;
import com.meritoki.retina.application.desktop.model.document.Data;
import com.meritoki.retina.application.desktop.model.document.Document;
import com.meritoki.retina.application.desktop.model.document.Page;
import com.meritoki.retina.application.desktop.model.document.Project;

/**
 *
 * @author osvaldo.rodriguez
 */
public class Matrix extends javax.swing.JDialog {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2052352120762179195L;
	private static org.apache.logging.log4j.Logger logger = LogManager.getLogger(Matrix.class.getName());
    private Model model = null;

    /**
     * Creates new form Page
     */
    public Matrix(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Matrix");
        initComponents();
    }

    public void setModel(Model model) {
        logger.debug("setModel(" + model + ")");
        this.model = model;
        this.init();
    }

    public void init() {
    	logger.debug("init()");
        this.initLabel();
        this.initList();
    }

    public void initLabel() {
        logger.debug("initLabel()");
        Document document = (this.model != null) ? this.model.getDocument() : null;
        Project project = (document != null) ? document.getProject() : null;
        Page page = (project != null) ? project.getPage() : null;
        int pageIndex = (project != null) ? project.getIndex() : 0;
        this.indexValueLabel.setText(pageIndex + "");
        this.uuidValueLabel.setText((page != null) ? page.uuid : "");
    }

    public void initList() {
        logger.debug("initList()");
        Document document = (this.model != null) ? this.model.getDocument() : null;
        Project project = (document != null) ? document.getProject() : null;
        Page page = (project != null) ? project.getPage():null;
        int index = (page != null) ? page.getIndex() : 0;
        List<Data> dataList = (page != null) ? page.getDataList() : null;
        this.initDataList(dataList);
        this.setDataListSelectedIndex(index);
    }

    public void initDataList(List<Data> dataList) {
        logger.debug("initDataList(" + dataList + ")");
        DefaultListModel<String> defaultListModel = new DefaultListModel<>();
        if (dataList != null && dataList.size() > 0) {
            for (int i = 0; i < dataList.size(); i++) {
                defaultListModel.addElement(dataList.get(i).uuid);
            }
        }
        this.dataList.setModel(defaultListModel);
    }

    public void setDataListSelectedIndex(int index) {
        this.dataList.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataList = new javax.swing.JList();
        indexLabel = new javax.swing.JLabel();
        indexValueLabel = new javax.swing.JLabel();
        uuidLabel = new javax.swing.JLabel();
        uuidValueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageScriptScrollPane = new javax.swing.JScrollPane();
        imageScriptTextArea = new javax.swing.JTextArea();
        executePageScriptButton = new javax.swing.JButton();
        resetPageScriptButton = new javax.swing.JButton();
        setImageList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dataList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(dataList);

        indexLabel.setText("Index:");

        indexValueLabel.setText("null");

        uuidLabel.setText("UUID:");

        uuidValueLabel.setText("null");

        jLabel1.setText("List");

        imageScriptTextArea.setColumns(20);
        imageScriptTextArea.setRows(5);
        imageScriptScrollPane.setViewportView(imageScriptTextArea);

        executePageScriptButton.setText("Execute");
        executePageScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executePageScriptButtonActionPerformed(evt);
            }
        });

        resetPageScriptButton.setText("Reset");
        resetPageScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPageScriptButtonActionPerformed(evt);
            }
        });

        setImageList.setText("Set");
        setImageList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setImageListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(uuidLabel)
                                                                        .addComponent(indexLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(uuidValueLabel)
                                                                        .addComponent(indexValueLabel)))
                                                        .addComponent(jLabel1))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(imageScriptScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(resetPageScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(executePageScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(setImageList, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(indexValueLabel)
                                        .addComponent(indexLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(uuidValueLabel)
                                        .addComponent(uuidLabel))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imageScriptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(executePageScriptButton)
                                        .addComponent(resetPageScriptButton)
                                        .addComponent(setImageList))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executePageScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executePageScriptButtonActionPerformed
        String value = this.imageScriptTextArea.getText();
        Document document = (this.model != null) ? this.model.getDocument() : null;
        Project project = (document != null) ? document.getProject() : null;
        this.model.variable.script.setPageList(project.getPageList());
        try {
            this.model.variable.script.sortDataMatrix(value);
        } catch (Exception ex) {
            System.err.println(ex);
        }
//        this.initDataList(this.pageList.get(this.model.project.getIndex()).getDataList());
    }//GEN-LAST:event_executePageScriptButtonActionPerformed

    private void resetPageScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPageScriptButtonActionPerformed
        Document document = (this.model != null) ? this.model.getDocument() : null;
        Project project = (document != null) ? document.getProject() : null;
    	this.initDataList(project.getPageList().get(project.getIndex()).getDataList());
    }//GEN-LAST:event_resetPageScriptButtonActionPerformed

    private void setImageListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setImageListActionPerformed
        Document document = (this.model != null) ? this.model.getDocument() : null;
        Project project = (document != null) ? document.getProject() : null;
    	project.setPageList(this.model.variable.pageList);
        this.imageScriptTextArea.setText("");
    }//GEN-LAST:event_setImageListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Matrix dialog = new Matrix(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList dataList;
    private javax.swing.JButton executePageScriptButton;
    private javax.swing.JScrollPane imageScriptScrollPane;
    private javax.swing.JTextArea imageScriptTextArea;
    private javax.swing.JLabel indexLabel;
    private javax.swing.JLabel indexValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetPageScriptButton;
    private javax.swing.JButton setImageList;
    private javax.swing.JLabel uuidLabel;
    private javax.swing.JLabel uuidValueLabel;
    // End of variables declaration//GEN-END:variables
}
