package org.retina.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.retina.model.cayenne.persistent.Page;

/**
 * Class _Model was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Model extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> UUID = Property.create("uuid", String.class);
    public static final Property<List<Page>> PAGE_LIST = Property.create("pageList", List.class);

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    public void addToPageList(Page obj) {
        addToManyTarget("pageList", obj, true);
    }
    public void removeFromPageList(Page obj) {
        removeToManyTarget("pageList", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Page> getPageList() {
        return (List<Page>)readProperty("pageList");
    }


}
