package org.retina.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.retina.model.cayenne.persistent.Model;
import org.retina.model.cayenne.persistent.Shape;

/**
 * Class _Page was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Page extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> UUID = Property.create("uuid", String.class);
    public static final Property<Model> MODEL = Property.create("model", Model.class);
    public static final Property<List<Shape>> SHAPE_LIST = Property.create("shapeList", List.class);

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    public void setModel(Model model) {
        setToOneTarget("model", model, true);
    }

    public Model getModel() {
        return (Model)readProperty("model");
    }


    public void addToShapeList(Shape obj) {
        addToManyTarget("shapeList", obj, true);
    }
    public void removeFromShapeList(Shape obj) {
        removeToManyTarget("shapeList", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Shape> getShapeList() {
        return (List<Shape>)readProperty("shapeList");
    }


}
