package org.retina.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.retina.model.cayenne.persistent.Page;

/**
 * Class _Shape was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Shape extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> UUID = Property.create("uuid", String.class);
    public static final Property<Page> PAGE = Property.create("page", Page.class);

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    public void setPage(Page page) {
        setToOneTarget("page", page, true);
    }

    public Page getPage() {
        return (Page)readProperty("page");
    }


}
