
title: Meritoki Retina
logo: ./Splash.png
description: Meritoki Retina is a desktop application for data rescue and training machine learning algorithms
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-176777850-1
