/*
 * Copyright 2019 osvaldo.rodriguez.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.retina.view.dialog;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import org.apache.logging.log4j.LogManager;
import org.retina.model.Model;

/**
 *
 * @author osvaldo.rodriguez
 */
public class Page extends javax.swing.JDialog {

    static org.apache.logging.log4j.Logger logger = LogManager.getLogger(Page.class.getName());
    private Model model;
    private List<org.retina.model.Image> imageList;
     
    /**
     * Creates new form Page
     */
    public Page(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Page");
        initComponents();
    }
    
    public void setModel(Model model){
        logger.debug("setModel("+model+")");
        this.model = model;
        this.init();
    }
    
    public void init(){
        this.initLabel();
        this.initList();
    }
    
    public void initLabel() {
        logger.debug("initLabel()");
        org.retina.model.Image image = (this.model != null)?this.model.getImage():null;
        org.retina.model.Page page = (image != null)?image.getPage():null;
        int imageIndex = (this.model != null)? this.model.getIndex():0;
        List<org.retina.model.Image> imageList = this.model.getImageList();
        this.indexValueLabel.setText(imageIndex+"");
        this.uuidValueLabel.setText((page!=null)?page.uuid:"");
    }
    
    public void initList() {
        logger.debug("initList()");
        org.retina.model.Image image = this.model.getImage();
        org.retina.model.Page page = (image != null)?image.getPage():null;
        int index = (image != null)?image.getIndex():0;
        List<org.retina.model.Data> dataList = (page != null)?page.getDataList():null;
        this.initDataList(dataList);
        this.setDataListSelectedIndex(index);
    }
    
    public void initDataList(List<org.retina.model.Data> dataList) {
        if(dataList!=null&&dataList.size()>0)
            logger.info("initDataList("+dataList+")");
        DefaultListModel defaultListModel = new DefaultListModel();
        if(dataList != null){
            for(int i=0;i<dataList.size(); i++) {
                defaultListModel.addElement(dataList.get(i).uuid);    
            }
        }
        this.dataList.setModel(defaultListModel);
    }
    
    public void setDataListSelectedIndex(int index){
        this.dataList.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataList = new javax.swing.JList();
        indexLabel = new javax.swing.JLabel();
        indexValueLabel = new javax.swing.JLabel();
        uuidLabel = new javax.swing.JLabel();
        uuidValueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageScriptScrollPane = new javax.swing.JScrollPane();
        imageScriptTextArea = new javax.swing.JTextArea();
        executePageScriptButton = new javax.swing.JButton();
        resetPageScriptButton = new javax.swing.JButton();
        setImageList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dataList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dataList);

        indexLabel.setText("Index:");

        indexValueLabel.setText("null");

        uuidLabel.setText("UUID:");

        uuidValueLabel.setText("null");

        jLabel1.setText("List");

        imageScriptTextArea.setColumns(20);
        imageScriptTextArea.setRows(5);
        imageScriptScrollPane.setViewportView(imageScriptTextArea);

        executePageScriptButton.setText("Execute");
        executePageScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executePageScriptButtonActionPerformed(evt);
            }
        });

        resetPageScriptButton.setText("Reset");
        resetPageScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPageScriptButtonActionPerformed(evt);
            }
        });

        setImageList.setText("Set");
        setImageList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setImageListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uuidLabel)
                                    .addComponent(indexLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uuidValueLabel)
                                    .addComponent(indexValueLabel)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imageScriptScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resetPageScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executePageScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setImageList, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexValueLabel)
                    .addComponent(indexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uuidValueLabel)
                    .addComponent(uuidLabel))
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageScriptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executePageScriptButton)
                    .addComponent(resetPageScriptButton)
                    .addComponent(setImageList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executePageScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executePageScriptButtonActionPerformed
        String value = this.imageScriptTextArea.getText();
        this.imageList = new ArrayList<>(this.model.getImageList());
        this.model.getScript().setImageList(this.imageList);
        try {
            this.model.getScript().page(value);
        } catch (Exception ex) {
            System.err.println(ex);
        }
        this.initDataList(this.imageList.get(this.model.getIndex()).getPage().getDataList());
    }//GEN-LAST:event_executePageScriptButtonActionPerformed

    private void resetPageScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPageScriptButtonActionPerformed
        this.initDataList(this.model.getImageList().get(this.model.getIndex()).getPage().getDataList());
    }//GEN-LAST:event_resetPageScriptButtonActionPerformed

    private void setImageListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setImageListActionPerformed
        this.model.setImageList(this.imageList);
        this.imageScriptTextArea.setText("");
    }//GEN-LAST:event_setImageListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Page dialog = new Page(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList dataList;
    private javax.swing.JButton executePageScriptButton;
    private javax.swing.JScrollPane imageScriptScrollPane;
    private javax.swing.JTextArea imageScriptTextArea;
    private javax.swing.JLabel indexLabel;
    private javax.swing.JLabel indexValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetPageScriptButton;
    private javax.swing.JButton setImageList;
    private javax.swing.JLabel uuidLabel;
    private javax.swing.JLabel uuidValueLabel;
    // End of variables declaration//GEN-END:variables
}
